services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
#    user: root
    environment:
      # This parameter will pass .env contents to PHP container. This is
      # required by settings.php file.
      PHP_FPM_CLEAR_ENV: "no"
      # PHPUnit Drupal testing configurations
      SIMPLETEST_BASE_URL: "http://nginx"
      SIMPLETEST_DB: "sqlite://localhost//dev/shm/test.sqlite"
#      SIMPLETEST_DB: "mysql://${DB_USER}:${DB_PASSWORD}@mariadb/${DB_NAME}#tests_"
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - ./code:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - ./code:/var/www/html:cached

  chrome:
    image: drupalci/webdriver-chromedriver:production
    container_name: "${PROJECT_NAME}_chrome"
    ulimits:
      core:
        soft: -1
        hard: -1
    ports:
      - "4444:4444"
      - "9515:9515"
    entrypoint:
      - chromedriver
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="
