name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PATH: './modules/custom'

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH }}

      - name: Run echo
        run: ls -la ./

      - name: Prepare environment
        uses: "${{ env.PATH }}/.github/actions/drupal-docker"

      - name: Run echo
        run: ls -la ./modules/custom
