name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: './.github/actions/drupal-docker'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: './modules/custom'

      - name: Finished
        run: ls -la ./
